draft-ietf-suit-manifest-02.cddl
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
=> Fix CDDL nits

draft-ietf-suit-manifest.md
Other PRs need to be merged first in order to complete this PR.
=> Updating Interpreter Behavior Section

draft-ietf-suit-manifest.cddl
Refactor CDDL to be more idiomatic
Add explicit extension points
Reorganise to add several new groups with better naming
Simplify structure
=> Refactor CDDL

draft-ietf-suit-manifest.cddl, draft-ietf-suit-manifest.md
=> Update CDDL and specifications for review comments 

draft-ietf-suit-manifest.md
As discussed in virtual interim, rename offset to slot.
=> Change offset condition to slot condition

draft-ietf-suit-manifest.md
As discussed in virtual interim, rename Garbage Collect to Unlink
=> Rename Garbage Collect to Unlink

draft-ietf-suit-manifest.md
Define the behaviour of a manifest processor when it is disrupted.
=> Add disruption resilience text

draft-ietf-suit-manifest.cddl
Addresses https://github.com/suit-wg/manifest-spec/issues/66
Signed-off-by: Akira Tsukamoto <akira.tsukamoto@aist.go.jp>
=> Hackathon114: Fix SUIT_Parameters as extensible socket

draft-ietf-suit-manifest.md
Fixes #63
* Make CBOR tag registrations suggested
* Add registration template
* Add tables for each metadata structure
=> Responses to IANA early evaluation

draft-ietf-suit-manifest.cddl, draft-ietf-suit-manifest.md
* Rename "run" to "invoke
* Rename "common sequence" to "shared sequence"
* Add clarifying text about Run Sequence when Strict Order = False
* Clarify that "suit-invoke" sequence may also contain image checks if necessary
* Add direct-write command and parameter, and content check condition
* Add clarifying text explaining stop conditions for try-each
=> Update for review comments including small writes

draft-ietf-suit-manifest.md
=> Close #81 (update references)

draft-ietf-suit-manifest.md
=> Address 91: Fix markdown artefact in code block

draft-ietf-suit-manifest.cddl, draft-ietf-suit-manifest.md
=> Address 97: Added internationalisation support to suit-text

draft-ietf-suit-manifest.md
=> Address Reporting Policy

draft-ietf-suit-manifest.md
=> Address 95: Clarify authentication block

draft-ietf-suit-manifest.md
=> Addresses 89: Clarify system state validation

draft-ietf-suit-manifest.md
=> guidance on what "small" and "large" mean in suit-parameter-content

draft-ietf-suit-manifest.md
=> Addresses-86: Clarify permissions required

draft-ietf-suit-manifest.md
=> Address 92: Clarify pseudocode

draft-ietf-suit-manifest.md
=> Address-87: Clarify environment where signature verification can be skipped

draft-ietf-suit-manifest.md
=> Address 90: Clarify resilience options

draft-ietf-suit-manifest.md
=> Address 93: Clarify Strict Order

draft-ietf-suit-manifest.md
=> Change manifest processor resume after execute to normative MAY

draft-ietf-suit-manifest.md
=> Address-94: Clarify parallel processing halt conditions

draft-ietf-suit-manifest.md
=> Address 99: Clarify invocation and fetch options

draft-ietf-suit-manifest.md
=> Clarify suit-parameter-soft-failure

draft-ietf-suit-manifest.md
=> Address 79: Clarify integrated payload template

draft-ietf-suit-manifest.md
This PR adds a mapping from RFC9124 security and usability requirements to the features of the manifest that implement them. There are several features that are TBD, particularly around file types and compression.
=> Initial pass at addressing issue #107

draft-ietf-suit-manifest.md
Here is the feedback from Roman:
https://mailarchive.ietf.org/arch/msg/suit/X9xOpl1QyLYPbFjnJIfWYxhLs2E/
=> Addressed Feedback from Roman

draft-ietf-suit-manifest.md
It is moved to draft-ietf-suit-update-management .
=> Remove text-version-required

draft-ietf-suit-manifest.md
Updates that cover additional review feedback
* Update obsolete reference: RFC4122bis has been published.
* Expand IoT in abstract
=> Editorial updates

draft-ietf-suit-manifest.html, draft-ietf-suit-manifest.md, draft-ietf-suit-manifest.txt, draft-ietf-suit-manifest.xml
Add normative reference to CDDL
=> additional-discuss

draft-ietf-suit-manifest.md
Fixes #149: Moves COSE_Alg to Normative
Fixes #151: Simplifies resilience requirements
Fixes #150: Moves Implementation Conformance Matrix out of the Appendix
=> Review fixes

draft-ietf-suit-manifest.md
A bad-refactor removed some grammar. This commit restores it
Fixes #157
=> Fix a bad refactor

draft-ietf-suit-manifest.md
=> Rename DNS Prefix to IANA UUID Namespace ID DNS

draft-ietf-suit-manifest.md
=> Spell out MCU
